// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Echart: typeof import('./src/components/Echart/index.vue')['default']
    ElButton: typeof import('element-ui/lib/button')['default']
    ElButtonGroup: typeof import('element-ui/lib/button-group')['default']
  }
}

export { }
